version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Expose the application port
    depends_on:
      - db  # Depend on the database service

  db:
    image: mysql  # Use the MySQL image
    environment:
      MYSQL_DATABASE: clustered_data  # Specify the database name
      MYSQL_USER: root  # Specify the MySQL username
      MYSQL_PASSWORD: admin  # Specify the MySQL password
      MYSQL_ROOT_PASSWORD: admin  # Specify the MySQL root password
    ports:
      - "3306:3306"  # Expose the MySQL port
